apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: appliance
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/crt-nshift-appliance-tenant/appliance/appliance@sha256:3ce3e77425469b9765e32399ddd642d5908ac11f6ae0448ec4bf6df3bbe49cc2
        name: my-go
        resources: {}
status: {}
