apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: appliance
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/crt-nshift-appliance-tenant/appliance/appliance@sha256:aa2a678ea71544884281ce7f802da2f4b06973a027293678fced7d0a1e4d048e
        name: my-go
        resources: {}
status: {}
